# Generated by Django 2.2.16 on 2023-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230325_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Вставьте изображение готового блюда', upload_to='data/images/', verbose_name='Иллюстрация'),
        ),
    ]
