# Generated by Django 2.2.16 on 2023-03-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230328_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient_in_Recipe',
        ),
    ]
