# Generated by Django 2.2.16 on 2023-03-31 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_auto_20230329_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.Recipe', verbose_name='Избранный рецепт')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorers',
            field=models.ManyToManyField(blank=True, help_text='Выберите избранные рецепты', related_name='favorites', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранные рецепты'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('favorer', 'favorite'), name='unique_favorite'),
        ),
    ]
