# Generated by Django 2.2.16 on 2023-03-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0014_auto_20230331_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='recipes.Recipe', verbose_name='Рецепт для покупки')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='buyers',
            field=models.ManyToManyField(blank=True, help_text='Выберите рецепты для покупки', related_name='purchases', through='recipes.Cart', to=settings.AUTH_USER_MODEL, verbose_name='Список рецептов в корзине'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('buyer', 'purchase'), name='unique_purchase'),
        ),
    ]
